'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3053
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On



Partial Public Class _Default

    '''<summary>
    '''styleLiteral control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents styleLiteral As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''Form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''f_offset control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents f_offset As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''f_loggedIn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents f_loggedIn As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''f_parm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents f_parm As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''f_data control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents f_data As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''loginPanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents loginPanel As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''f_userName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents f_userName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''f_password control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents f_password As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''loginButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents loginButton As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''changePasswordButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents changePasswordButton As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''cpRow_1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cpRow_1 As Global.System.Web.UI.WebControls.TableRow

    '''<summary>
    '''newPasswordTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents newPasswordTextBox As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''cpRow_2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cpRow_2 As Global.System.Web.UI.WebControls.TableRow

    '''<summary>
    '''newPasswordAgainTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents newPasswordAgainTextBox As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''cpRow_3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cpRow_3 As Global.System.Web.UI.WebControls.TableRow

    '''<summary>
    '''confirmChangePasswordButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents confirmChangePasswordButton As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''changePasswordResponseLegacy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents changePasswordResponseLegacy As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''loginPanelNewInterface control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents loginPanelNewInterface As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''userNameNewInterface control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents userNameNewInterface As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''passwordNewInterface control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents passwordNewInterface As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''loginButtonNewInterface control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents loginButtonNewInterface As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''changePasswordButtonNewInterface control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents changePasswordButtonNewInterface As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''changePasswordResponseNewInterface control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents changePasswordResponseNewInterface As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''changePasswordPanelNewInterface control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents changePasswordPanelNewInterface As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''newPasswordTextBoxNewInterface control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents newPasswordTextBoxNewInterface As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''newPasswordAgainTextBoxNewInterface control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents newPasswordAgainTextBoxNewInterface As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''confirmChangePasswordButtonNewInterface control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents confirmChangePasswordButtonNewInterface As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''responseTable control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents responseTable As Global.System.Web.UI.WebControls.Table

    '''<summary>
    '''changePasswordResponse control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents changePasswordResponse As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''adminChoiceTable control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents adminChoiceTable As Global.System.Web.UI.WebControls.Table

    '''<summary>
    '''recordingsButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents recordingsButton As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''adminButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents adminButton As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''closeButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents closeButton As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''adminTable control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents adminTable As Global.System.Web.UI.WebControls.Table

    '''<summary>
    '''administratorsLit0 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents administratorsLit0 As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''administratorsLit1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents administratorsLit1 As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''administratorsUsernameText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents administratorsUsernameText As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''administratorsPasswordText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents administratorsPasswordText As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''addAdministratorButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents addAdministratorButton As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''supervisorsLit0 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents supervisorsLit0 As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''supervisorsLit1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents supervisorsLit1 As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''supervisorsLit2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents supervisorsLit2 As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''supervisorsUsernameText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents supervisorsUsernameText As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''supervisorsPasswordText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents supervisorsPasswordText As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''supervisorsDataText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents supervisorsDataText As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''addSupervisorButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents addSupervisorButton As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''adminOKButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents adminOKButton As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''searchPanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents searchPanel As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''f_startDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents f_startDate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''f_endDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents f_endDate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''f_extension control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents f_extension As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''f_destination control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents f_destination As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''f_callId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents f_callId As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TestButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TestButton As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''calendar1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents calendar1 As Global.System.Web.UI.WebControls.Calendar

    '''<summary>
    '''calendar2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents calendar2 As Global.System.Web.UI.WebControls.Calendar

    '''<summary>
    '''f_tag control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents f_tag As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''startTime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents startTime As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''endTime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents endTime As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''callTypeList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents callTypeList As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''logoutButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents logoutButton As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''clearButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents clearButton As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''submitButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents submitButton As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''legacyCheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents legacyCheckBox As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''newInterfaceSearchPanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents newInterfaceSearchPanel As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''newInterfaceLogoutButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents newInterfaceLogoutButton As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''newInterfaceClearButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents newInterfaceClearButton As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''newInterfaceSubmitButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents newInterfaceSubmitButton As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''timeSpanNewInterfaceDropDownList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents timeSpanNewInterfaceDropDownList As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ignoreTimeNewInterfaceCheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ignoreTimeNewInterfaceCheckBox As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''startTimeNewInterfaceLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents startTimeNewInterfaceLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''startTimeNewInterfaceDropDownList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents startTimeNewInterfaceDropDownList As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''endTimeNewInterfaceLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents endTimeNewInterfaceLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''endTimeNewInterfaceDropDownList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents endTimeNewInterfaceDropDownList As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''calendar3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents calendar3 As Global.System.Web.UI.WebControls.Calendar

    '''<summary>
    '''calendar4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents calendar4 As Global.System.Web.UI.WebControls.Calendar

    '''<summary>
    '''extensionTextBoxNewInterface control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents extensionTextBoxNewInterface As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''externalNumberTextBoxNewInterface control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents externalNumberTextBoxNewInterface As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''callIdTextBoxNewInterface control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents callIdTextBoxNewInterface As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''directionDropDownListNewInterface control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents directionDropDownListNewInterface As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''summaryPanelNewInterface control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents summaryPanelNewInterface As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''prevButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents prevButton As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''recordsLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents recordsLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''nextButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents nextButton As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''myRepeater control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents myRepeater As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''myLiteral control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents myLiteral As Global.System.Web.UI.WebControls.Literal
End Class
